name: flutter_storybook_example
description: Demonstrates how to use the flutter_storybook plugin.
publish_to: "none"

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_storybook:
    path: "../"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: .SF UI Text
      fonts:
        - asset: fonts/SF/SF-UI-Text-Ultrathin.otf
          weight: 100
        - asset: fonts/SF/SF-UI-Text-Light.otf
          weight: 200
        - asset: fonts/SF/SF-UI-Text-Regular.otf
          weight: 400
        - asset: fonts/SF/SF-UI-Text-Medium.ttf
          weight: 500
        - asset: fonts/SF/SF-UI-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF/SF-UI-Text-Bold.otf
          weight: 700
        - asset: fonts/SF/SF-UI-Text-Heavy.otf
          weight: 800
    - family: .SF UI Display
      fonts:
        - asset: fonts/SF/SF-UI-Display-Ultralight.otf
          weight: 100
        - asset: fonts/SF/SF-UI-Display-Light.otf
          weight: 200
        - asset: fonts/SF/SF-UI-Display-Thin.otf
          weight: 300
        - asset: fonts/SF/SF-UI-Display-Regular.otf
          weight: 400
        - asset: fonts/SF/SF-UI-Display-Medium.otf
          weight: 500
        - asset: fonts/SF/SF-UI-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF/SF-UI-Display-Bold.otf
          weight: 700
        - asset: fonts/SF/SF-UI-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF/SF-UI-Display-Black.otf
          weight: 900
